# Generated by Django 5.1.3 on 2025-02-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EverydayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveBigIntegerField(default=1, unique=True)),
                ('quote_1', models.TextField(blank=True, null=True)),
                ('quote_2', models.TextField(blank=True, null=True)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('quantity_task', models.PositiveBigIntegerField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='static/img')),
                ('image_2', models.ImageField(null=True, upload_to='static/img')),
                ('image_3', models.ImageField(null=True, upload_to='static/img')),
                ('trailer_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
                ('status', models.CharField(choices=[('Sports', 'Спорт'), ('Mental growth and recovery', 'Прокачка интелекта и востановление'), ('Relaxation', 'отдых'), ('Professional skill-building', 'Прокачка професиональных навыков'), ('Theoretical study', 'теория')], default='planned', max_length=40, verbose_name='Статус дня')),
            ],
            options={
                'verbose_name': 'Ежедневное задание',
                'verbose_name_plural': 'Ежедневные задания',
                'ordering': ['day'],
            },
        ),
    ]
