# Generated by Django 5.1.3 on 2025-02-16 16:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EverydayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveBigIntegerField(default=1, unique=True)),
                ('quote_1', models.TextField(blank=True, null=True)),
                ('quote_2', models.TextField(blank=True, null=True)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('quantity_task', models.PositiveBigIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('trailer_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
                ('status', models.CharField(choices=[('Sports', 'Спорт'), ('Mental growth and recovery', 'Прокачка интелекта и востановление'), ('Relaxation', 'отдых'), ('Professional skill-building', 'Прокачка професиональных навыков'), ('Theoretical study', 'теория'), ('adaptation', 'адаптация')], default='planned', max_length=40, verbose_name='Статус дня')),
            ],
            options={
                'verbose_name': 'Ежедневное задание',
                'verbose_name_plural': 'Ежедневные задания',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('level', models.PositiveIntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
