# Generated by Django 5.1.3 on 2025-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_pullups',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум в подтягиваниях'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_pushups',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум в отжиманиях'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_run_1km',
            field=models.FloatField(blank=True, null=True, verbose_name='Время на 1 км (мин)'),
        ),
    ]
