# Generated by Django 5.1.3 on 2025-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaytask',
            name='status',
            field=models.CharField(choices=[('Sports', 'Спорт'), ('Mental growth and recovery', 'Прокачка интелекта и востановление'), ('Relaxation', 'отдых'), ('Professional skill-building', 'Прокачка професиональных навыков'), ('Theoretical study', 'теория'), ('adaptation', 'адаптация')], default='planned', max_length=40, verbose_name='Статус дня'),
        ),
    ]
